# fly.toml app configuration file generated for linebot-swappay on 2023-06-26T17:30:53+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "linebot-swappay"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[mounts]
source="linebot_swappay_data"
destination="/app/data"